"""Binary storage behind a small interface. Only object keys live in the
database. LocalStorage is for development/tests; S3Storage talks to any
S3-compatible provider (Cloudflare R2, Backblaze B2, AWS S3, MinIO)."""
import logging
import re
import uuid
from pathlib import Path
from typing import Protocol
from urllib.parse import urlparse

import boto3
from botocore.config import Config
from botocore.exceptions import ClientError, ConnectTimeoutError, EndpointConnectionError
from starlette.concurrency import run_in_threadpool

from backend.core.config import Settings

logger = logging.getLogger("mediscan.storage")

_KEY_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]{0,510}$")


def _validate_key(key: str) -> None:
    """Keys are generated by the server, but never trust that: no leading
    slash, no '..', no empty path segments, restricted alphabet."""
    if not _KEY_RE.match(key) or ".." in key or "//" in key:
        raise ValueError("Invalid storage key")


class StorageService(Protocol):
    async def put(self, key: str, data: bytes, content_type: str) -> None: ...
    async def get(self, key: str) -> bytes:
        """Raises FileNotFoundError if the object does not exist."""
        ...
    async def delete(self, key: str) -> None:
        """Idempotent: deleting a missing object is not an error."""
        ...
    async def check(self) -> None:
        """Write, read back and delete a tiny object; raises on any problem."""
        ...


async def _roundtrip(storage: StorageService) -> None:
    key = f"healthcheck/{uuid.uuid4()}"
    payload = b"mediscan-storage-check"
    await storage.put(key, payload, "text/plain")
    try:
        if await storage.get(key) != payload:
            raise RuntimeError("Storage read-back did not match what was written")
    finally:
        await storage.delete(key)


# ---------------------------------------------------------------- local
class LocalStorage:
    """Files under a base directory. Development and tests only."""

    def __init__(self, base_dir: Path):
        self.base = Path(base_dir).resolve()

    def _path(self, key: str) -> Path:
        _validate_key(key)
        path = (self.base / key).resolve()
        if not path.is_relative_to(self.base):
            raise ValueError("Invalid storage key")
        return path

    async def put(self, key: str, data: bytes, content_type: str) -> None:
        def _write() -> None:
            path = self._path(key)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

        await run_in_threadpool(_write)

    async def get(self, key: str) -> bytes:
        return await run_in_threadpool(lambda: self._path(key).read_bytes())

    async def delete(self, key: str) -> None:
        await run_in_threadpool(lambda: self._path(key).unlink(missing_ok=True))

    async def check(self) -> None:
        await _roundtrip(self)


# ------------------------------------------------------------------- s3
class S3Storage:
    """Private bucket accessed with server-held credentials. boto3 is
    synchronous, so calls run in a threadpool (clients are thread-safe)."""

    def __init__(self, *, endpoint_url: str | None, bucket: str, access_key_id: str,
                 secret_access_key: str, region: str = "auto"):
        self.bucket = bucket
        self._client = boto3.client(
            "s3",
            endpoint_url=endpoint_url or None,
            aws_access_key_id=access_key_id,
            aws_secret_access_key=secret_access_key,
            region_name=region,
            config=Config(
                signature_version="s3v4",
                retries={"max_attempts": 3, "mode": "standard"},
                connect_timeout=5,
                read_timeout=30,
                s3={"addressing_style": "path"} if endpoint_url else {},
                # Newer SDK defaults add checksum headers that Cloudflare R2
                # rejects; only send them when an operation requires them.
                request_checksum_calculation="when_required",
                response_checksum_validation="when_required",
            ),
        )

    async def put(self, key: str, data: bytes, content_type: str) -> None:
        _validate_key(key)
        await run_in_threadpool(
            lambda: self._client.put_object(
                Bucket=self.bucket, Key=key, Body=data, ContentType=content_type
            )
        )

    async def get(self, key: str) -> bytes:
        _validate_key(key)

        def _get() -> bytes:
            try:
                return self._client.get_object(Bucket=self.bucket, Key=key)["Body"].read()
            except ClientError as exc:
                if exc.response.get("Error", {}).get("Code") in ("NoSuchKey", "404"):
                    raise FileNotFoundError(key) from exc
                raise

        return await run_in_threadpool(_get)

    async def delete(self, key: str) -> None:
        _validate_key(key)
        await run_in_threadpool(
            lambda: self._client.delete_object(Bucket=self.bucket, Key=key)
        )

    async def check(self) -> None:
        # No HeadBucket: bucket-scoped object tokens are not allowed to call it.
        await _roundtrip(self)


# -------------------------------------------------------------- helpers
def describe_storage_error(exc: Exception) -> str:
    """Plain-language diagnosis. Never includes credentials."""
    if isinstance(exc, ClientError):
        code = exc.response.get("Error", {}).get("Code", "")
        if code in ("InvalidAccessKeyId", "SignatureDoesNotMatch"):
            return ("The access key or secret is wrong. Check S3_ACCESS_KEY_ID and "
                    "S3_SECRET_ACCESS_KEY (no quotes, no trailing spaces).")
        if code in ("AccessDenied", "403", "Forbidden"):
            return ("Access denied. The API token needs 'Object Read & Write' "
                    "permission and must include this bucket.")
        if code in ("NoSuchBucket", "404"):
            return ("Bucket not found. Check S3_BUCKET spelling, and that the endpoint "
                    "belongs to the same account.")
        return f"The storage service returned error code '{code}'."
    if isinstance(exc, (EndpointConnectionError, ConnectTimeoutError)):
        return "Could not reach the endpoint. Check S3_ENDPOINT_URL and your network."
    return f"{type(exc).__name__}: {exc}"


def build_storage_service(settings: Settings) -> StorageService:
    if settings.storage_backend == "s3":
        assert settings.s3_bucket and settings.s3_access_key_id and settings.s3_secret_access_key
        return S3Storage(
            endpoint_url=settings.s3_endpoint_url,
            bucket=settings.s3_bucket,
            access_key_id=settings.s3_access_key_id,
            secret_access_key=settings.s3_secret_access_key.get_secret_value(),
            region=settings.s3_region,
        )
    return LocalStorage(settings.storage_local_dir)


def endpoint_host(settings: Settings) -> str:
    return urlparse(settings.s3_endpoint_url).netloc if settings.s3_endpoint_url else "(AWS default)"
