# Generated by Django 6.0.3 on 2026-04-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Official name of the organization. e.g., "Maiduguri Specialist Hospital"',
                        max_length=255,
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("diagnostic_centre", "Diagnostic Centre"),
                            ("clinic", "Clinic"),
                            ("telemedicine", "Telemedicine Platform"),
                            ("other", "Other"),
                        ],
                        help_text="Type of healthcare facility",
                        max_length=50,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("abia", "Abia"),
                            ("adamawa", "Adamawa"),
                            ("akwa_ibom", "Akwa Ibom"),
                            ("anambra", "Anambra"),
                            ("bauchi", "Bauchi"),
                            ("bayelsa", "Bayelsa"),
                            ("borno", "Borno"),
                            ("cross_river", "Cross River"),
                            ("delta", "Delta"),
                            ("ebonyi", "Ebonyi"),
                            ("edo", "Edo"),
                            ("ekiti", "Ekiti"),
                            ("enugu", "Enugu"),
                            ("fct", "Federal Capital Territory"),
                            ("gombe", "Gombe"),
                            ("imo", "Imo"),
                            ("jigawa", "Jigawa"),
                            ("kaduna", "Kaduna"),
                            ("kano", "Kano"),
                            ("katsina", "Katsina"),
                            ("kebbi", "Kebbi"),
                            ("kogi", "Kogi"),
                            ("kwara", "Kwara"),
                            ("lagos", "Lagos"),
                            ("nasarawa", "Nasarawa"),
                            ("niger", "Niger"),
                            ("ogun", "Ogun"),
                            ("ondo", "Ondo"),
                            ("osun", "Osun"),
                            ("oyo", "Oyo"),
                            ("plateau", "Plateau"),
                            ("rivers", "Rivers"),
                            ("sokoto", "Sokoto"),
                            ("taraba", "Taraba"),
                            ("yobe", "Yobe"),
                            ("zamfara", "Zamfara"),
                        ],
                        help_text="Nigerian state where the organization is located",
                        max_length=50,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Organization contact phone number. Used for account recovery and billing inquiries.",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo displayed in dashboard header",
                        null=True,
                        upload_to="org_logos/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this organization can access MediScan services",
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Trial"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        help_text="Current subscription tier",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["-created_at"],
            },
        ),
    ]
